language: generic

services:
  - docker

before_install:
- echo "docker compose creating and start"
- docker-compose build

script:
- docker-compose up -d 
- docker-compose exec bmart-app ./gradlew clean build
- docker-compose exec bmart-app ./gradlew integrationTest

after_success:
- echo "Test Success"
