language: generic
sudo: required
dist: focal

services:
  - docker

before_install:
- echo "docker compose creating and start"

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/bmart-app:develop -f Dockerfile-app .
- docker push $DOCKER_USERNAME/bmart-app:develop
- docker build -t $DOCKER_USERNAME/nginx-app:develop -f Dockerfile-nginx  .
- docker push $DOCKER_USERNAME/nginx-app:develop
- docker-compose up -d 

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS-ACCESS-KEY"
  secret_access_key:
    secure: "$AWS-SECRET-ACCESS-KEY"
  region: "ap-northeast-2"
  app: "docker-bmart-app"
  env: "Docker-bmart-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-284256502692"
  on:
    branch: develop
