language: generic
sudo: required
dist: focal

services:
  - docker

before_install:
- echo "docker compose creating and start"

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kimgyeongha/bmart-app:develop -f Dockerfile-app .
- docker push kimgyeongha/bmart-app:develops
- docker build -t kimgyeongha/nginx-app:develop -f Dockerfile-nginx  .
- docker push kimgyeongha/nginx-app:develop
- docker-compose up -d 

after_success:
- echo "Test Success"
