sudo: required

language: generic

services:
  - docker

before_install:
- echo "docker compose creating and start"
- docker-compose build

script:
- docker-compose up -d bmart-app
- docker-compose exec bmart-app asciidoctor

after_success:
- echo "Test Success"
