language: generic

services:
  - docker

before_install:
- echo "docker compose creating and start"
- docker-compose build

script:
- docker build -t kimgyeongha/bmart-app:develop  /bmart_dockerfile/.
- docker build -t kimgyeongha/nginx-app:develop  /nginx_dockerfile/.
- docker push kimgyeongha/bmart-app:develop
- docker push kimgyeongha/nginx-app:develop
- docker-compose up -d 

after_success:
- echo "Test Success"
