sudo: required

language: generic

services:
  - docker

before_install:
- echo "docker compose creating and start"
- docker-compose build

script:
- docker-compose up -d bmart-app
- docker-compose exec bmart-app test-command CI=true test-- --coverage

after_success:
- echo "Test Success"
