language: generic
sudo: required
dist: focal

services:
  - docker

before_install:
- echo "docker compose creating and start"

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/bmart-app:develop \
      --build-arg url=$DATABASE_URL \
      --build-arg username=$DATABASE_USERNAME \
      --build-arg password=$DATABASE_PASSWORD \
      --build-arg naver_client_id=$NAVER_CLIENT_ID \
      --build-arg naver_client_secret=$NAVER_CLIENT_SECRET \
      --build-arg kakao_client_id=$KAKAO_CLIENT_ID \
      --build-arg kakao_client_secret=$KAKAO_CLIENT_SECRET \ -f Dockerfile-app .
- docker push $DOCKER_USERNAME/bmart-app:develop
- docker build -t $DOCKER_USERNAME/nginx-app:develop \
      --build-arg url=$DATABASE_URL \
      --build-arg username=$DATABASE_USERNAME \
      --build-arg password=$DATABASE_PASSWORD \
      --build-arg naver_client_id=$NAVER_CLIENT_ID \
      --build-arg naver_client_secret=$NAVER_CLIENT_SECRET \
      --build-arg kakao_client_id=$KAKAO_CLIENT_ID \
      --build-arg kakao_client_secret=$KAKAO_CLIENT_SECRET \ -f Dockerfile-nginx .
- docker push $DOCKER_USERNAME/nginx-app:develop

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "ap-northeast-2"
  app: "docker-bmart-app"
  env: "Docker-bmart-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-284256502692"
  bucket_path : "docker-bmart-app"
  on:
    branch: develop
