language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - chmod +x ./gradlew
  - docker-compose up -d --build

script:
  - docker exec bmart-app ./gradlew integrationTest

after_script:
  - docker-compose down
