language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - chmod +x ./gradlew
  - docker-compose up -d --build

script:
  - ./gradlew clean build
  - ./gradlew test
  - docker exec <container_name> ./gradlew integrationTest

after_script:
  - docker-compose down

# (옵션) 필요에 따라 다음과 같이 추가적인 설정을 할 수 있습니다.
# notifications:
#   email:
#     recipients:
#       - your_email@example.com
#     on_success: always
#     on_failure: always
