language: generic
sudo: required
dist: focal

services:
  - docker

before_install:
- echo "docker compose creating and start"

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kimgyeongha/bmart-app:develop -f Dockerfile-app .
- docker push kimgyeongha/bmart-app:develop
- docker build -t kimgyeongha/nginx-app:develop -f Dockerfile-nginx  .
- docker push kimgyeongha/nginx-app:develop
- docker-compose up -d 

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS-ACCESS-KEY-ID"
  secret_access_key:
    secure: "$AWS-ACCESS-KEY"
  region: "ap-northeast-2"
  app: "Docker-bmat-app"
  env: "Docker-bmat-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-284256502692"
