FROM gradle:latest  AS builder 
WORKDIR /bmart-app
COPY . .
RUN chmod +x ./gradlew 
RUN ./gradlew build

FROM openjdk:17-alpine
COPY --from=builder /bmart-app/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"] 
